def on_a_pressed():
    global bush, flowers, bigFlowers, mushrooms
    if mySprite.overlaps_with(mySprite2):
        mySprite2.destroy()
        bush = 5
    elif mySprite.overlaps_with(mySprite3):
        mySprite3.destroy()
        flowers = 5
    elif mySprite.overlaps_with(mySprite4):
        mySprite4.destroy()
        bigFlowers = 5
    elif mySprite.overlaps_with(mySprite5):
        mySprite5.destroy()
        mushrooms = 5
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

mushrooms = 0
bigFlowers = 0
flowers = 0
bush = 0
mySprite: Sprite = None
mySprite5: Sprite = None
mySprite4: Sprite = None
mySprite3: Sprite = None
mySprite2: Sprite = None
mySprite2 = sprites.create(img("""
        ....................
            ....................
            .........1..........
            ......661d1.........
            .....177717766......
            ....1d177777677.....
            ..6.717777c77177....
            ...7c77767771d17....
            ...77677766771777...
            ..1777766677777767..
            .1d1776717676777c7..
            .7177661d176777777..
            .77767771777777176..
            .677c77777c7671d17..
            .77777777777767176..
            .667776776777777767.
            ...76776766676766...
            ....................
            ....................
            ....................
    """),
    SpriteKind.player)
mySprite2.set_position(140, 55)
mySprite3 = sprites.create(img("""
        ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            .......2............
            ......222...2.......
            ......252..252..2...
            ...2...2...222.222..
            ..252..6....2..252..
            ..222..66...6...2...
            ...2..66....6...66..
            ...6...6.6.666..6...
            .6...6.........6..6.
            ....................
    """),
    SpriteKind.player)
mySprite3.set_position(30, 230)
mySprite4 = sprites.create(img("""
        ....................
            ....................
            ....................
            ....................
            ....................
            .....bb...b..77b....
            ....bbbb7bbb7.bbb...
            ...bbbbb.bbbb.bbbb..
            ...bbcc7bbbbc7bbbb..
            ...bbb.7bbbb7.cbbb..
            ..bbbc..bbbb7..cbb..
            ...bc...7bcc.7..cb..
            ..bc...7.bb7.7..bb..
            ......77.bc...7.cbb.
            ......7..c7...7.....
            ......7...7....7....
            .....7....7.....7...
            ....77....7.....7...
            ....................
            ....................
    """),
    SpriteKind.player)
mySprite4.set_position(115, 80)
mySprite5 = sprites.create(img("""
        ........................
            .....bbbbb..............
            ....b33333bb............
            ...b33331113b...........
            ...b333311113b..........
            ..b1133331113bc.........
            .b11133333333bbb........
            bb1133113333bbbc.bbbb...
            cbb3311113bbddbcb3311b..
            cbbbbddddbbdddcbb33113c.
            .cbbbbddbbbddbbddb3333bc
            ..ccbbbbbbbbccbddbbbddbc
            ....cccccccb.ccbbbbbddbc
            ......b1ddb....ccbbbbbc.
            .....b11ddb.....bccccc..
            .....b1ddbb.....bddb....
    """),
    SpriteKind.player)
mySprite5.set_position(207, 230)
mySprite = sprites.create(img("""
        . . . . . . . . . . . . . . . . 
            . . . . . . . . a . . . . . . . 
            . . . . . . . a a . . . . . . . 
            . . . . . . a a a a . . . . . . 
            . . . . a b a a a a b a . . . . 
            . . . a a b b a a b b a a . . . 
            . . e a a a b b b b a a a . . . 
            . . e e a a a a a a a a e e . . 
            . . e e e d f d d f d e e e . . 
            . . e e e d f d d f d e e e . . 
            . . . e e d d d d d d e e . . . 
            . . . d d f d d d d f d d . . . 
            . . d b c b a b b a b f b d . . 
            . . d d f a a a a a a f d d . . 
            . . . . c b a a a a b c . . . . 
            . . . . . f f f f f f . . . . .
    """),
    SpriteKind.player)
mySprite.set_position(225, 5)
controller.move_sprite(mySprite, 100, 100)
tiles.set_tilemap(tilemap("""
    level2
"""))
scene.camera_follow_sprite(mySprite)